// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/fleet.proto

package fleetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceService_Register_FullMethodName        = "/fleet.v1.DeviceService/Register"
	DeviceService_TelemetryStream_FullMethodName = "/fleet.v1.DeviceService/TelemetryStream"
	DeviceService_GetAssignment_FullMethodName   = "/fleet.v1.DeviceService/GetAssignment"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// DeviceService: the device-facing (data-plane) API.
// ---------------------------------------------------------------------------
type DeviceServiceClient interface {
	// Register is an idempotent upsert of a device's identity/labels.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// TelemetryStream is a client-streaming heartbeat channel: a device sends a
	// continuous stream of health/metric reports (and config apply acks). The
	// server replies once when the stream closes.
	TelemetryStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryReport, TelemetryStreamSummary], error)
	// GetAssignment is the pull half of desired-state reconciliation: a device
	// polls for the config version the control plane wants it to run. Config is
	// distributed by pull (like a kubelet / IoT device shadow), not pushed over
	// the telemetry stream.
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DeviceService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) TelemetryStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryReport, TelemetryStreamSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceService_ServiceDesc.Streams[0], DeviceService_TelemetryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryReport, TelemetryStreamSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceService_TelemetryStreamClient = grpc.ClientStreamingClient[TelemetryReport, TelemetryStreamSummary]

func (c *deviceServiceClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assignment)
	err := c.cc.Invoke(ctx, DeviceService_GetAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// DeviceService: the device-facing (data-plane) API.
// ---------------------------------------------------------------------------
type DeviceServiceServer interface {
	// Register is an idempotent upsert of a device's identity/labels.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// TelemetryStream is a client-streaming heartbeat channel: a device sends a
	// continuous stream of health/metric reports (and config apply acks). The
	// server replies once when the stream closes.
	TelemetryStream(grpc.ClientStreamingServer[TelemetryReport, TelemetryStreamSummary]) error
	// GetAssignment is the pull half of desired-state reconciliation: a device
	// polls for the config version the control plane wants it to run. Config is
	// distributed by pull (like a kubelet / IoT device shadow), not pushed over
	// the telemetry stream.
	GetAssignment(context.Context, *GetAssignmentRequest) (*Assignment, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDeviceServiceServer) TelemetryStream(grpc.ClientStreamingServer[TelemetryReport, TelemetryStreamSummary]) error {
	return status.Error(codes.Unimplemented, "method TelemetryStream not implemented")
}
func (UnimplementedDeviceServiceServer) GetAssignment(context.Context, *GetAssignmentRequest) (*Assignment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignment not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_TelemetryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceServiceServer).TelemetryStream(&grpc.GenericServerStream[TelemetryReport, TelemetryStreamSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceService_TelemetryStreamServer = grpc.ClientStreamingServer[TelemetryReport, TelemetryStreamSummary]

func _DeviceService_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DeviceService_Register_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _DeviceService_GetAssignment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TelemetryStream",
			Handler:       _DeviceService_TelemetryStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/fleet.proto",
}

const (
	AdminService_ListDevices_FullMethodName   = "/fleet.v1.AdminService/ListDevices"
	AdminService_CreateRollout_FullMethodName = "/fleet.v1.AdminService/CreateRollout"
	AdminService_GetRollout_FullMethodName    = "/fleet.v1.AdminService/GetRollout"
	AdminService_WatchRollout_FullMethodName  = "/fleet.v1.AdminService/WatchRollout"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// AdminService: the operator-facing (control-plane) API.
// ---------------------------------------------------------------------------
type AdminServiceClient interface {
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// CreateRollout begins a staged config rollout (canary -> full). Returns the
	// rollout id; progress is observed via GetRollout / WatchRollout.
	CreateRollout(ctx context.Context, in *CreateRolloutRequest, opts ...grpc.CallOption) (*CreateRolloutResponse, error)
	GetRollout(ctx context.Context, in *GetRolloutRequest, opts ...grpc.CallOption) (*Rollout, error)
	// WatchRollout is a server-streaming feed of rollout state-machine events:
	// the event log is replayed, then live events stream until the rollout
	// reaches a terminal state or the client disconnects.
	WatchRollout(ctx context.Context, in *WatchRolloutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutEvent], error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateRollout(ctx context.Context, in *CreateRolloutRequest, opts ...grpc.CallOption) (*CreateRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRolloutResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetRollout(ctx context.Context, in *GetRolloutRequest, opts ...grpc.CallOption) (*Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rollout)
	err := c.cc.Invoke(ctx, AdminService_GetRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) WatchRollout(ctx context.Context, in *WatchRolloutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_WatchRollout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRolloutRequest, RolloutEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchRolloutClient = grpc.ServerStreamingClient[RolloutEvent]

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// AdminService: the operator-facing (control-plane) API.
// ---------------------------------------------------------------------------
type AdminServiceServer interface {
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// CreateRollout begins a staged config rollout (canary -> full). Returns the
	// rollout id; progress is observed via GetRollout / WatchRollout.
	CreateRollout(context.Context, *CreateRolloutRequest) (*CreateRolloutResponse, error)
	GetRollout(context.Context, *GetRolloutRequest) (*Rollout, error)
	// WatchRollout is a server-streaming feed of rollout state-machine events:
	// the event log is replayed, then live events stream until the rollout
	// reaches a terminal state or the client disconnects.
	WatchRollout(*WatchRolloutRequest, grpc.ServerStreamingServer[RolloutEvent]) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedAdminServiceServer) CreateRollout(context.Context, *CreateRolloutRequest) (*CreateRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRollout not implemented")
}
func (UnimplementedAdminServiceServer) GetRollout(context.Context, *GetRolloutRequest) (*Rollout, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRollout not implemented")
}
func (UnimplementedAdminServiceServer) WatchRollout(*WatchRolloutRequest, grpc.ServerStreamingServer[RolloutEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchRollout not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateRollout(ctx, req.(*CreateRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetRollout(ctx, req.(*GetRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_WatchRollout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRolloutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).WatchRollout(m, &grpc.GenericServerStream[WatchRolloutRequest, RolloutEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchRolloutServer = grpc.ServerStreamingServer[RolloutEvent]

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _AdminService_ListDevices_Handler,
		},
		{
			MethodName: "CreateRollout",
			Handler:    _AdminService_CreateRollout_Handler,
		},
		{
			MethodName: "GetRollout",
			Handler:    _AdminService_GetRollout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRollout",
			Handler:       _AdminService_WatchRollout_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/fleet.proto",
}
