// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/fleet.proto

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health reflects the last-known operational state of a device.
type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_HEALTHY     Health = 1
	Health_HEALTH_DEGRADED    Health = 2
	Health_HEALTH_OFFLINE     Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_OFFLINE",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_HEALTHY":     1,
		"HEALTH_DEGRADED":    2,
		"HEALTH_OFFLINE":     3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fleet_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_api_fleet_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{0}
}

type RolloutState int32

const (
	RolloutState_ROLLOUT_STATE_UNSPECIFIED RolloutState = 0
	RolloutState_ROLLOUT_STATE_PENDING     RolloutState = 1
	RolloutState_ROLLOUT_STATE_IN_PROGRESS RolloutState = 2
	RolloutState_ROLLOUT_STATE_SUCCEEDED   RolloutState = 3
	RolloutState_ROLLOUT_STATE_HALTED      RolloutState = 4
	RolloutState_ROLLOUT_STATE_ROLLED_BACK RolloutState = 5
)

// Enum value maps for RolloutState.
var (
	RolloutState_name = map[int32]string{
		0: "ROLLOUT_STATE_UNSPECIFIED",
		1: "ROLLOUT_STATE_PENDING",
		2: "ROLLOUT_STATE_IN_PROGRESS",
		3: "ROLLOUT_STATE_SUCCEEDED",
		4: "ROLLOUT_STATE_HALTED",
		5: "ROLLOUT_STATE_ROLLED_BACK",
	}
	RolloutState_value = map[string]int32{
		"ROLLOUT_STATE_UNSPECIFIED": 0,
		"ROLLOUT_STATE_PENDING":     1,
		"ROLLOUT_STATE_IN_PROGRESS": 2,
		"ROLLOUT_STATE_SUCCEEDED":   3,
		"ROLLOUT_STATE_HALTED":      4,
		"ROLLOUT_STATE_ROLLED_BACK": 5,
	}
)

func (x RolloutState) Enum() *RolloutState {
	p := new(RolloutState)
	*p = x
	return p
}

func (x RolloutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fleet_proto_enumTypes[1].Descriptor()
}

func (RolloutState) Type() protoreflect.EnumType {
	return &file_api_fleet_proto_enumTypes[1]
}

func (x RolloutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutState.Descriptor instead.
func (RolloutState) EnumDescriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{1}
}

type WaveState int32

const (
	WaveState_WAVE_STATE_UNSPECIFIED WaveState = 0
	WaveState_WAVE_STATE_PENDING     WaveState = 1
	WaveState_WAVE_STATE_RUNNING     WaveState = 2
	WaveState_WAVE_STATE_PROMOTED    WaveState = 3
	WaveState_WAVE_STATE_FAILED      WaveState = 4
)

// Enum value maps for WaveState.
var (
	WaveState_name = map[int32]string{
		0: "WAVE_STATE_UNSPECIFIED",
		1: "WAVE_STATE_PENDING",
		2: "WAVE_STATE_RUNNING",
		3: "WAVE_STATE_PROMOTED",
		4: "WAVE_STATE_FAILED",
	}
	WaveState_value = map[string]int32{
		"WAVE_STATE_UNSPECIFIED": 0,
		"WAVE_STATE_PENDING":     1,
		"WAVE_STATE_RUNNING":     2,
		"WAVE_STATE_PROMOTED":    3,
		"WAVE_STATE_FAILED":      4,
	}
)

func (x WaveState) Enum() *WaveState {
	p := new(WaveState)
	*p = x
	return p
}

func (x WaveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaveState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fleet_proto_enumTypes[2].Descriptor()
}

func (WaveState) Type() protoreflect.EnumType {
	return &file_api_fleet_proto_enumTypes[2]
}

func (x WaveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaveState.Descriptor instead.
func (WaveState) EnumDescriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{2}
}

// Config is a versioned, opaque configuration blob. The control plane never
// interprets the blob; devices do. `version` is the identity used for rollout
// bookkeeping and desired-state reconciliation.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *Config) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TargetSelector chooses which devices a rollout applies to. `all` targets the
// whole fleet; otherwise a device must carry every label in match_labels.
type TargetSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	MatchLabels   map[string]string      `protobuf:"bytes,2,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetSelector) Reset() {
	*x = TargetSelector{}
	mi := &file_api_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSelector) ProtoMessage() {}

func (x *TargetSelector) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSelector.ProtoReflect.Descriptor instead.
func (*TargetSelector) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *TargetSelector) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *TargetSelector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

// Device is the control-plane's record of a single fleet member.
type Device struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Model  string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Health Health                 `protobuf:"varint,4,opt,name=health,proto3,enum=fleet.v1.Health" json:"health,omitempty"`
	// Version the device last reported as successfully applied ("running").
	AppliedVersion string `protobuf:"bytes,5,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	LastSeenUnixMs int64  `protobuf:"varint,6,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_api_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *Device) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *Device) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

// ConfigApplyResult is a device's ack (or nack) after attempting to converge to
// a desired config version. It is the signal the rollout guardrail acts on.
type ConfigApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplyResult) Reset() {
	*x = ConfigApplyResult{}
	mi := &file_api_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyResult) ProtoMessage() {}

func (x *ConfigApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyResult.ProtoReflect.Descriptor instead.
func (*ConfigApplyResult) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigApplyResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigApplyResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigApplyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired config the device should converge to at registration time.
	Desired       *Config `protobuf:"bytes,1,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetDesired() *Config {
	if x != nil {
		return x.Desired
	}
	return nil
}

type TelemetryReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Health          Health                 `protobuf:"varint,3,opt,name=health,proto3,enum=fleet.v1.Health" json:"health,omitempty"`
	// Version the device is currently running.
	AppliedVersion string `protobuf:"bytes,4,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// Optional: set when this report acks the outcome of a config apply attempt.
	ApplyResult   *ConfigApplyResult `protobuf:"bytes,5,opt,name=apply_result,json=applyResult,proto3" json:"apply_result,omitempty"`
	Metrics       map[string]float64 `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_api_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryReport) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryReport) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *TelemetryReport) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *TelemetryReport) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *TelemetryReport) GetApplyResult() *ConfigApplyResult {
	if x != nil {
		return x.ApplyResult
	}
	return nil
}

func (x *TelemetryReport) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type TelemetryStreamSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportsReceived int32                  `protobuf:"varint,1,opt,name=reports_received,json=reportsReceived,proto3" json:"reports_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryStreamSummary) Reset() {
	*x = TelemetryStreamSummary{}
	mi := &file_api_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryStreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryStreamSummary) ProtoMessage() {}

func (x *TelemetryStreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryStreamSummary.ProtoReflect.Descriptor instead.
func (*TelemetryStreamSummary) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryStreamSummary) GetReportsReceived() int32 {
	if x != nil {
		return x.ReportsReceived
	}
	return 0
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_api_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *GetAssignmentRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desired       *Config                `protobuf:"bytes,1,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_api_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *Assignment) GetDesired() *Config {
	if x != nil {
		return x.Desired
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_api_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{10}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_api_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type CreateRolloutRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Target *TargetSelector        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Cumulative wave percentages, e.g. [5, 25, 100]. Each wave targets that
	// percent of the selected fleet; the last wave must be 100.
	WavePercents []int32 `protobuf:"varint,3,rep,packed,name=wave_percents,json=wavePercents,proto3" json:"wave_percents,omitempty"`
	// Fraction of a wave (0..1) allowed to fail before the guardrail halts and
	// rolls back. A wave failure rate strictly greater than this halts.
	FailureThreshold float64 `protobuf:"fixed64,4,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	// How long a wave must stay healthy before it is promoted to the next wave.
	HealthWindowMs int64 `protobuf:"varint,5,opt,name=health_window_ms,json=healthWindowMs,proto3" json:"health_window_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRolloutRequest) Reset() {
	*x = CreateRolloutRequest{}
	mi := &file_api_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolloutRequest) ProtoMessage() {}

func (x *CreateRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolloutRequest.ProtoReflect.Descriptor instead.
func (*CreateRolloutRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRolloutRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateRolloutRequest) GetTarget() *TargetSelector {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CreateRolloutRequest) GetWavePercents() []int32 {
	if x != nil {
		return x.WavePercents
	}
	return nil
}

func (x *CreateRolloutRequest) GetFailureThreshold() float64 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *CreateRolloutRequest) GetHealthWindowMs() int64 {
	if x != nil {
		return x.HealthWindowMs
	}
	return 0
}

type CreateRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolloutResponse) Reset() {
	*x = CreateRolloutResponse{}
	mi := &file_api_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolloutResponse) ProtoMessage() {}

func (x *CreateRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolloutResponse.ProtoReflect.Descriptor instead.
func (*CreateRolloutResponse) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRolloutResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type GetRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolloutRequest) Reset() {
	*x = GetRolloutRequest{}
	mi := &file_api_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolloutRequest) ProtoMessage() {}

func (x *GetRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolloutRequest.ProtoReflect.Descriptor instead.
func (*GetRolloutRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *GetRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type WatchRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRolloutRequest) Reset() {
	*x = WatchRolloutRequest{}
	mi := &file_api_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRolloutRequest) ProtoMessage() {}

func (x *WatchRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRolloutRequest.ProtoReflect.Descriptor instead.
func (*WatchRolloutRequest) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *WatchRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type Wave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Percent       int32                  `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	TargetCount   int32                  `protobuf:"varint,3,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	AppliedOk     int32                  `protobuf:"varint,4,opt,name=applied_ok,json=appliedOk,proto3" json:"applied_ok,omitempty"`
	AppliedFail   int32                  `protobuf:"varint,5,opt,name=applied_fail,json=appliedFail,proto3" json:"applied_fail,omitempty"`
	State         WaveState              `protobuf:"varint,6,opt,name=state,proto3,enum=fleet.v1.WaveState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wave) Reset() {
	*x = Wave{}
	mi := &file_api_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wave) ProtoMessage() {}

func (x *Wave) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wave.ProtoReflect.Descriptor instead.
func (*Wave) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *Wave) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Wave) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Wave) GetTargetCount() int32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *Wave) GetAppliedOk() int32 {
	if x != nil {
		return x.AppliedOk
	}
	return 0
}

func (x *Wave) GetAppliedFail() int32 {
	if x != nil {
		return x.AppliedFail
	}
	return 0
}

func (x *Wave) GetState() WaveState {
	if x != nil {
		return x.State
	}
	return WaveState_WAVE_STATE_UNSPECIFIED
}

type Rollout struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config      *Config                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Target      *TargetSelector        `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	State       RolloutState           `protobuf:"varint,4,opt,name=state,proto3,enum=fleet.v1.RolloutState" json:"state,omitempty"`
	CurrentWave int32                  `protobuf:"varint,5,opt,name=current_wave,json=currentWave,proto3" json:"current_wave,omitempty"`
	Waves       []*Wave                `protobuf:"bytes,6,rep,name=waves,proto3" json:"waves,omitempty"`
	// Version devices are reverted to if the guardrail rolls the rollout back.
	PreviousVersion string   `protobuf:"bytes,7,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	TargetDeviceIds []string `protobuf:"bytes,8,rep,name=target_device_ids,json=targetDeviceIds,proto3" json:"target_device_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rollout) Reset() {
	*x = Rollout{}
	mi := &file_api_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rollout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rollout) ProtoMessage() {}

func (x *Rollout) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rollout.ProtoReflect.Descriptor instead.
func (*Rollout) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *Rollout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rollout) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Rollout) GetTarget() *TargetSelector {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Rollout) GetState() RolloutState {
	if x != nil {
		return x.State
	}
	return RolloutState_ROLLOUT_STATE_UNSPECIFIED
}

func (x *Rollout) GetCurrentWave() int32 {
	if x != nil {
		return x.CurrentWave
	}
	return 0
}

func (x *Rollout) GetWaves() []*Wave {
	if x != nil {
		return x.Waves
	}
	return nil
}

func (x *Rollout) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *Rollout) GetTargetDeviceIds() []string {
	if x != nil {
		return x.TargetDeviceIds
	}
	return nil
}

type RolloutEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RolloutId       string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// One of: CREATED, WAVE_STARTED, WAVE_PROMOTED, DEVICE_OK, DEVICE_FAIL,
	// HALTED, ROLLED_BACK, SUCCEEDED.
	Kind          string       `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Message       string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	State         RolloutState `protobuf:"varint,5,opt,name=state,proto3,enum=fleet.v1.RolloutState" json:"state,omitempty"`
	Wave          int32        `protobuf:"varint,6,opt,name=wave,proto3" json:"wave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutEvent) Reset() {
	*x = RolloutEvent{}
	mi := &file_api_fleet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutEvent) ProtoMessage() {}

func (x *RolloutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_fleet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutEvent.ProtoReflect.Descriptor instead.
func (*RolloutEvent) Descriptor() ([]byte, []int) {
	return file_api_fleet_proto_rawDescGZIP(), []int{18}
}

func (x *RolloutEvent) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *RolloutEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *RolloutEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RolloutEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RolloutEvent) GetState() RolloutState {
	if x != nil {
		return x.State
	}
	return RolloutState_ROLLOUT_STATE_UNSPECIFIED
}

func (x *RolloutEvent) GetWave() int32 {
	if x != nil {
		return x.Wave
	}
	return 0
}

var File_api_fleet_proto protoreflect.FileDescriptor

const file_api_fleet_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/fleet.proto\x12\bfleet.v1\"X\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb0\x01\n" +
	"\x0eTargetSelector\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12L\n" +
	"\fmatch_labels\x18\x02 \x03(\v2).fleet.v1.TargetSelector.MatchLabelsEntryR\vmatchLabels\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06labels\x18\x02 \x03(\v2\x1c.fleet.v1.Device.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12(\n" +
	"\x06health\x18\x04 \x01(\x0e2\x10.fleet.v1.HealthR\x06health\x12'\n" +
	"\x0fapplied_version\x18\x05 \x01(\tR\x0eappliedVersion\x12)\n" +
	"\x11last_seen_unix_ms\x18\x06 \x01(\x03R\x0elastSeenUnixMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x11ConfigApplyResult\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb1\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.fleet.v1.RegisterRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x10RegisterResponse\x12*\n" +
	"\adesired\x18\x01 \x01(\v2\x10.fleet.v1.ConfigR\adesired\"\xeb\x02\n" +
	"\x0fTelemetryReport\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12(\n" +
	"\x06health\x18\x03 \x01(\x0e2\x10.fleet.v1.HealthR\x06health\x12'\n" +
	"\x0fapplied_version\x18\x04 \x01(\tR\x0eappliedVersion\x12>\n" +
	"\fapply_result\x18\x05 \x01(\v2\x1b.fleet.v1.ConfigApplyResultR\vapplyResult\x12@\n" +
	"\ametrics\x18\x06 \x03(\v2&.fleet.v1.TelemetryReport.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"C\n" +
	"\x16TelemetryStreamSummary\x12)\n" +
	"\x10reports_received\x18\x01 \x01(\x05R\x0freportsReceived\"3\n" +
	"\x14GetAssignmentRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"8\n" +
	"\n" +
	"Assignment\x12*\n" +
	"\adesired\x18\x01 \x01(\v2\x10.fleet.v1.ConfigR\adesired\"\x14\n" +
	"\x12ListDevicesRequest\"A\n" +
	"\x13ListDevicesResponse\x12*\n" +
	"\adevices\x18\x01 \x03(\v2\x10.fleet.v1.DeviceR\adevices\"\xee\x01\n" +
	"\x14CreateRolloutRequest\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.fleet.v1.ConfigR\x06config\x120\n" +
	"\x06target\x18\x02 \x01(\v2\x18.fleet.v1.TargetSelectorR\x06target\x12#\n" +
	"\rwave_percents\x18\x03 \x03(\x05R\fwavePercents\x12+\n" +
	"\x11failure_threshold\x18\x04 \x01(\x01R\x10failureThreshold\x12(\n" +
	"\x10health_window_ms\x18\x05 \x01(\x03R\x0ehealthWindowMs\"6\n" +
	"\x15CreateRolloutResponse\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"2\n" +
	"\x11GetRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"4\n" +
	"\x13WatchRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"\xc6\x01\n" +
	"\x04Wave\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x05R\apercent\x12!\n" +
	"\ftarget_count\x18\x03 \x01(\x05R\vtargetCount\x12\x1d\n" +
	"\n" +
	"applied_ok\x18\x04 \x01(\x05R\tappliedOk\x12!\n" +
	"\fapplied_fail\x18\x05 \x01(\x05R\vappliedFail\x12)\n" +
	"\x05state\x18\x06 \x01(\x0e2\x13.fleet.v1.WaveStateR\x05state\"\xc3\x02\n" +
	"\aRollout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06config\x18\x02 \x01(\v2\x10.fleet.v1.ConfigR\x06config\x120\n" +
	"\x06target\x18\x03 \x01(\v2\x18.fleet.v1.TargetSelectorR\x06target\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.fleet.v1.RolloutStateR\x05state\x12!\n" +
	"\fcurrent_wave\x18\x05 \x01(\x05R\vcurrentWave\x12$\n" +
	"\x05waves\x18\x06 \x03(\v2\x0e.fleet.v1.WaveR\x05waves\x12)\n" +
	"\x10previous_version\x18\a \x01(\tR\x0fpreviousVersion\x12*\n" +
	"\x11target_device_ids\x18\b \x03(\tR\x0ftargetDeviceIds\"\xc9\x01\n" +
	"\fRolloutEvent\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12,\n" +
	"\x05state\x18\x05 \x01(\x0e2\x16.fleet.v1.RolloutStateR\x05state\x12\x12\n" +
	"\x04wave\x18\x06 \x01(\x05R\x04wave*]\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x12\n" +
	"\x0eHEALTH_OFFLINE\x10\x03*\xbd\x01\n" +
	"\fRolloutState\x12\x1d\n" +
	"\x19ROLLOUT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ROLLOUT_STATE_PENDING\x10\x01\x12\x1d\n" +
	"\x19ROLLOUT_STATE_IN_PROGRESS\x10\x02\x12\x1b\n" +
	"\x17ROLLOUT_STATE_SUCCEEDED\x10\x03\x12\x18\n" +
	"\x14ROLLOUT_STATE_HALTED\x10\x04\x12\x1d\n" +
	"\x19ROLLOUT_STATE_ROLLED_BACK\x10\x05*\x87\x01\n" +
	"\tWaveState\x12\x1a\n" +
	"\x16WAVE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WAVE_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12WAVE_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13WAVE_STATE_PROMOTED\x10\x03\x12\x15\n" +
	"\x11WAVE_STATE_FAILED\x10\x042\xeb\x01\n" +
	"\rDeviceService\x12A\n" +
	"\bRegister\x12\x19.fleet.v1.RegisterRequest\x1a\x1a.fleet.v1.RegisterResponse\x12P\n" +
	"\x0fTelemetryStream\x12\x19.fleet.v1.TelemetryReport\x1a .fleet.v1.TelemetryStreamSummary(\x01\x12E\n" +
	"\rGetAssignment\x12\x1e.fleet.v1.GetAssignmentRequest\x1a\x14.fleet.v1.Assignment2\xb3\x02\n" +
	"\fAdminService\x12J\n" +
	"\vListDevices\x12\x1c.fleet.v1.ListDevicesRequest\x1a\x1d.fleet.v1.ListDevicesResponse\x12P\n" +
	"\rCreateRollout\x12\x1e.fleet.v1.CreateRolloutRequest\x1a\x1f.fleet.v1.CreateRolloutResponse\x12<\n" +
	"\n" +
	"GetRollout\x12\x1b.fleet.v1.GetRolloutRequest\x1a\x11.fleet.v1.Rollout\x12G\n" +
	"\fWatchRollout\x12\x1d.fleet.v1.WatchRolloutRequest\x1a\x16.fleet.v1.RolloutEvent0\x01B0Z.github.com/ericsson-kuma/fleet-ctl/api/fleetpbb\x06proto3"

var (
	file_api_fleet_proto_rawDescOnce sync.Once
	file_api_fleet_proto_rawDescData []byte
)

func file_api_fleet_proto_rawDescGZIP() []byte {
	file_api_fleet_proto_rawDescOnce.Do(func() {
		file_api_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_fleet_proto_rawDesc), len(file_api_fleet_proto_rawDesc)))
	})
	return file_api_fleet_proto_rawDescData
}

var file_api_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_fleet_proto_goTypes = []any{
	(Health)(0),                    // 0: fleet.v1.Health
	(RolloutState)(0),              // 1: fleet.v1.RolloutState
	(WaveState)(0),                 // 2: fleet.v1.WaveState
	(*Config)(nil),                 // 3: fleet.v1.Config
	(*TargetSelector)(nil),         // 4: fleet.v1.TargetSelector
	(*Device)(nil),                 // 5: fleet.v1.Device
	(*ConfigApplyResult)(nil),      // 6: fleet.v1.ConfigApplyResult
	(*RegisterRequest)(nil),        // 7: fleet.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 8: fleet.v1.RegisterResponse
	(*TelemetryReport)(nil),        // 9: fleet.v1.TelemetryReport
	(*TelemetryStreamSummary)(nil), // 10: fleet.v1.TelemetryStreamSummary
	(*GetAssignmentRequest)(nil),   // 11: fleet.v1.GetAssignmentRequest
	(*Assignment)(nil),             // 12: fleet.v1.Assignment
	(*ListDevicesRequest)(nil),     // 13: fleet.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 14: fleet.v1.ListDevicesResponse
	(*CreateRolloutRequest)(nil),   // 15: fleet.v1.CreateRolloutRequest
	(*CreateRolloutResponse)(nil),  // 16: fleet.v1.CreateRolloutResponse
	(*GetRolloutRequest)(nil),      // 17: fleet.v1.GetRolloutRequest
	(*WatchRolloutRequest)(nil),    // 18: fleet.v1.WatchRolloutRequest
	(*Wave)(nil),                   // 19: fleet.v1.Wave
	(*Rollout)(nil),                // 20: fleet.v1.Rollout
	(*RolloutEvent)(nil),           // 21: fleet.v1.RolloutEvent
	nil,                            // 22: fleet.v1.TargetSelector.MatchLabelsEntry
	nil,                            // 23: fleet.v1.Device.LabelsEntry
	nil,                            // 24: fleet.v1.RegisterRequest.LabelsEntry
	nil,                            // 25: fleet.v1.TelemetryReport.MetricsEntry
}
var file_api_fleet_proto_depIdxs = []int32{
	22, // 0: fleet.v1.TargetSelector.match_labels:type_name -> fleet.v1.TargetSelector.MatchLabelsEntry
	23, // 1: fleet.v1.Device.labels:type_name -> fleet.v1.Device.LabelsEntry
	0,  // 2: fleet.v1.Device.health:type_name -> fleet.v1.Health
	24, // 3: fleet.v1.RegisterRequest.labels:type_name -> fleet.v1.RegisterRequest.LabelsEntry
	3,  // 4: fleet.v1.RegisterResponse.desired:type_name -> fleet.v1.Config
	0,  // 5: fleet.v1.TelemetryReport.health:type_name -> fleet.v1.Health
	6,  // 6: fleet.v1.TelemetryReport.apply_result:type_name -> fleet.v1.ConfigApplyResult
	25, // 7: fleet.v1.TelemetryReport.metrics:type_name -> fleet.v1.TelemetryReport.MetricsEntry
	3,  // 8: fleet.v1.Assignment.desired:type_name -> fleet.v1.Config
	5,  // 9: fleet.v1.ListDevicesResponse.devices:type_name -> fleet.v1.Device
	3,  // 10: fleet.v1.CreateRolloutRequest.config:type_name -> fleet.v1.Config
	4,  // 11: fleet.v1.CreateRolloutRequest.target:type_name -> fleet.v1.TargetSelector
	2,  // 12: fleet.v1.Wave.state:type_name -> fleet.v1.WaveState
	3,  // 13: fleet.v1.Rollout.config:type_name -> fleet.v1.Config
	4,  // 14: fleet.v1.Rollout.target:type_name -> fleet.v1.TargetSelector
	1,  // 15: fleet.v1.Rollout.state:type_name -> fleet.v1.RolloutState
	19, // 16: fleet.v1.Rollout.waves:type_name -> fleet.v1.Wave
	1,  // 17: fleet.v1.RolloutEvent.state:type_name -> fleet.v1.RolloutState
	7,  // 18: fleet.v1.DeviceService.Register:input_type -> fleet.v1.RegisterRequest
	9,  // 19: fleet.v1.DeviceService.TelemetryStream:input_type -> fleet.v1.TelemetryReport
	11, // 20: fleet.v1.DeviceService.GetAssignment:input_type -> fleet.v1.GetAssignmentRequest
	13, // 21: fleet.v1.AdminService.ListDevices:input_type -> fleet.v1.ListDevicesRequest
	15, // 22: fleet.v1.AdminService.CreateRollout:input_type -> fleet.v1.CreateRolloutRequest
	17, // 23: fleet.v1.AdminService.GetRollout:input_type -> fleet.v1.GetRolloutRequest
	18, // 24: fleet.v1.AdminService.WatchRollout:input_type -> fleet.v1.WatchRolloutRequest
	8,  // 25: fleet.v1.DeviceService.Register:output_type -> fleet.v1.RegisterResponse
	10, // 26: fleet.v1.DeviceService.TelemetryStream:output_type -> fleet.v1.TelemetryStreamSummary
	12, // 27: fleet.v1.DeviceService.GetAssignment:output_type -> fleet.v1.Assignment
	14, // 28: fleet.v1.AdminService.ListDevices:output_type -> fleet.v1.ListDevicesResponse
	16, // 29: fleet.v1.AdminService.CreateRollout:output_type -> fleet.v1.CreateRolloutResponse
	20, // 30: fleet.v1.AdminService.GetRollout:output_type -> fleet.v1.Rollout
	21, // 31: fleet.v1.AdminService.WatchRollout:output_type -> fleet.v1.RolloutEvent
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_fleet_proto_init() }
func file_api_fleet_proto_init() {
	if File_api_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_fleet_proto_rawDesc), len(file_api_fleet_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_fleet_proto_goTypes,
		DependencyIndexes: file_api_fleet_proto_depIdxs,
		EnumInfos:         file_api_fleet_proto_enumTypes,
		MessageInfos:      file_api_fleet_proto_msgTypes,
	}.Build()
	File_api_fleet_proto = out.File
	file_api_fleet_proto_goTypes = nil
	file_api_fleet_proto_depIdxs = nil
}
